<?php 
class Medicion_operaciones__model extends CI_Model {

    function __construct() {
        parent::__construct();
    }
    function save_medicion_operaciones($post){
        if(isset($post['campo'])){ 
        $this->db->where($post["campo"],$post[$post["campo"]]);
        $id=$post[$post["campo"]];
            unset($post['campo']);
            $this->db->update('medicion_operaciones',$post);
        }else{
            $this->db->insert('medicion_operaciones',$post);
            $id=$this->db->insert_id();
        }
        return $id;
        
    }
    function delete_medicion_operaciones($post){
        $this->db->set('ACTIVO','N');
        $this->db->where($post["campo"],$post[$post["campo"]]);
        $this->db->update('medicion_operaciones');
    }
    function edit_medicion_operaciones($post){
        $this->db->where($post["campo"],$post[$post["campo"]]);
        $datos=$this->db->get('medicion_operaciones',$post);
        return $datos=$datos->result();
    }
    function consult_medicion_operaciones($post){
            if(isset($post['IdMedicionOperaciones']))
        if($post['IdMedicionOperaciones']!="")
        $this->db->like('IdMedicionOperaciones',$post['IdMedicionOperaciones']);
                    if(isset($post['Supervisor']))
        if($post['Supervisor']!="")
        $this->db->like('Supervisor',$post['Supervisor']);
                    if(isset($post['FechaInicio']))
        if($post['FechaInicio']!="")
        $this->db->like('FechaInicio',$post['FechaInicio']);
                    if(isset($post['FechaFin']))
        if($post['FechaFin']!="")
        $this->db->like('FechaFin',$post['FechaFin']);
                    if(isset($post['Ruta']))
        if($post['Ruta']!="")
        $this->db->like('Ruta',$post['Ruta']);
                    if(isset($post['IdBus']))
        if($post['IdBus']!="")
        $this->db->like('IdBus',$post['IdBus']);
                    if(isset($post['Placa']))
        if($post['Placa']!="")
        $this->db->like('Placa',$post['Placa']);
                    if(isset($post['IdEmpresa']))
        if($post['IdEmpresa']!="")
        $this->db->like('IdEmpresa',$post['IdEmpresa']);
                    if(isset($post['CodigoBus']))
        if($post['CodigoBus']!="")
        $this->db->like('CodigoBus',$post['CodigoBus']);
                    if(isset($post['TipoMedicion']))
        if($post['TipoMedicion']!="")
        $this->db->like('TipoMedicion',$post['TipoMedicion']);
                    if(isset($post['VerificarRuteros']))
        if($post['VerificarRuteros']!="")
        $this->db->like('VerificarRuteros',$post['VerificarRuteros']);
                    if(isset($post['Aproximacion']))
        if($post['Aproximacion']!="")
        $this->db->like('Aproximacion',$post['Aproximacion']);
                    if(isset($post['CinturonSeguridad']))
        if($post['CinturonSeguridad']!="")
        $this->db->like('CinturonSeguridad',$post['CinturonSeguridad']);
                    if(isset($post['InformadoresVisuales']))
        if($post['InformadoresVisuales']!="")
        $this->db->like('InformadoresVisuales',$post['InformadoresVisuales']);
                    if(isset($post['InformadoresAuditivos']))
        if($post['InformadoresAuditivos']!="")
        $this->db->like('InformadoresAuditivos',$post['InformadoresAuditivos']);
                    if(isset($post['AvisoAuditivoPuertas']))
        if($post['AvisoAuditivoPuertas']!="")
        $this->db->like('AvisoAuditivoPuertas',$post['AvisoAuditivoPuertas']);
                    if(isset($post['Extintores']))
        if($post['Extintores']!="")
        $this->db->like('Extintores',$post['Extintores']);
                    if(isset($post['ManejoOperador']))
        if($post['ManejoOperador']!="")
        $this->db->like('ManejoOperador',$post['ManejoOperador']);
                    if(isset($post['SenalesEmergencia']))
        if($post['SenalesEmergencia']!="")
        $this->db->like('SenalesEmergencia',$post['SenalesEmergencia']);
                    if(isset($post['ParadasProgramadas']))
        if($post['ParadasProgramadas']!="")
        $this->db->like('ParadasProgramadas',$post['ParadasProgramadas']);
                    if(isset($post['UsoDotacion']))
        if($post['UsoDotacion']!="")
        $this->db->like('UsoDotacion',$post['UsoDotacion']);
                    if(isset($post['UsoEPP']))
        if($post['UsoEPP']!="")
        $this->db->like('UsoEPP',$post['UsoEPP']);
                    if(isset($post['ARLOperador']))
        if($post['ARLOperador']!="")
        $this->db->like('ARLOperador',$post['ARLOperador']);
                    if(isset($post['CarneOperador']))
        if($post['CarneOperador']!="")
        $this->db->like('CarneOperador',$post['CarneOperador']);
                    if(isset($post['CarneCodigoOperador']))
        if($post['CarneCodigoOperador']!="")
        $this->db->like('CarneCodigoOperador',$post['CarneCodigoOperador']);
                    if(isset($post['LicenciaConduccion']))
        if($post['LicenciaConduccion']!="")
        $this->db->like('LicenciaConduccion',$post['LicenciaConduccion']);
                    if(isset($post['DocumentacionVehiculo']))
        if($post['DocumentacionVehiculo']!="")
        $this->db->like('DocumentacionVehiculo',$post['DocumentacionVehiculo']);
                    if(isset($post['FechaVencimientoBotiquin']))
        if($post['FechaVencimientoBotiquin']!="")
        $this->db->like('FechaVencimientoBotiquin',$post['FechaVencimientoBotiquin']);
                    if(isset($post['FechaVencimientoExtintor']))
        if($post['FechaVencimientoExtintor']!="")
        $this->db->like('FechaVencimientoExtintor',$post['FechaVencimientoExtintor']);
                    if(isset($post['PlataformaDiscapacitados']))
        if($post['PlataformaDiscapacitados']!="")
        $this->db->like('PlataformaDiscapacitados',$post['PlataformaDiscapacitados']);
                    if(isset($post['Pito']))
        if($post['Pito']!="")
        $this->db->like('Pito',$post['Pito']);
                    if(isset($post['PitoReversa']))
        if($post['PitoReversa']!="")
        $this->db->like('PitoReversa',$post['PitoReversa']);
                    if(isset($post['InspeccionGeneralVehiculo']))
        if($post['InspeccionGeneralVehiculo']!="")
        $this->db->like('InspeccionGeneralVehiculo',$post['InspeccionGeneralVehiculo']);
                    if(isset($post['ValidarCodigoOperador']))
        if($post['ValidarCodigoOperador']!="")
        $this->db->like('ValidarCodigoOperador',$post['ValidarCodigoOperador']);
                    if(isset($post['FechaRegistro']))
        if($post['FechaRegistro']!="")
        $this->db->like('FechaRegistro',$post['FechaRegistro']);
                    if(isset($post['IdUsuarioRegistro']))
        if($post['IdUsuarioRegistro']!="")
        $this->db->like('IdUsuarioRegistro',$post['IdUsuarioRegistro']);
                                    $this->db->select('IdMedicionOperaciones');
                                $this->db->select('Supervisor');
                                $this->db->select('FechaInicio');
                                $this->db->select('FechaFin');
                                $this->db->select('Ruta');
                                $this->db->select('IdBus');
                                $this->db->select('IdEmpresa');
                                $this->db->select('CodigoBus');
                                $this->db->select('TipoMedicion');
                                $this->db->select('VerificarRuteros');
                                $this->db->select('Aproximacion');
                                $this->db->select('CinturonSeguridad');
                                $this->db->select('InformadoresVisuales');
                                $this->db->select('InformadoresAuditivos');
                                $this->db->select('AvisoAuditivoPuertas');
                                $this->db->select('Extintores');
                                $this->db->select('ManejoOperador');
                                $this->db->select('SenalesEmergencia');
                                $this->db->select('ParadasProgramadas');
                                $this->db->select('UsoDotacion');
                                $this->db->select('UsoEPP');
                                $this->db->select('ARLOperador');
                                $this->db->select('CarneOperador');
                                $this->db->select('CarneCodigoOperador');
                                $this->db->select('LicenciaConduccion');
                                $this->db->select('DocumentacionVehiculo');
                                $this->db->select('FechaVencimientoBotiquin');
                                $this->db->select('FechaVencimientoExtintor');
                                $this->db->select('PlataformaDiscapacitados');
                                $this->db->select('Pito');
                                $this->db->select('PitoReversa');
                                $this->db->select('InspeccionGeneralVehiculo');
                                $this->db->select('ValidarCodigoOperador');
                                $this->db->select('IdUsuarioRegistro');
                        $this->db->where('ACTIVO','S');
        $datos=$this->db->get('medicion_operaciones');
        $datos=$datos->result();
        return $datos;
    }
}
?>
